default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: hotels_api_development

test:
  <<: *default
  database: hotels_api_test

production:
  <<: *default
  pool: 30
  database: <%= ENV['HOTELS_API_DATABASE'] %>
  username: <%= ENV['HOTELS_API_DATABASE_USERNAME'] %>
  password: <%= ENV['HOTELS_API_DATABASE_PASSWORD'] %>
